# Generated by Django 6.0.3 on 2026-05-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_expense_amount_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('alimentacion', 'Alimentación'), ('educacion', 'Educación'), ('ocio', 'Ocio'), ('salud', 'Salud'), ('servicios', 'Servicios Públicos'), ('transporte', 'Transporte'), ('otros', 'Otros')], default='otros', max_length=100, verbose_name='Categoría'),
        ),
    ]
