# Generated by Django 6.0.3 on 2026-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='salario_minimo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Salario Mínimo'),
        ),
    ]
